config/routes.rb
require "resque/server"

Gemfilestats::Application.routes.draw do
  mount Resque::Server.new, :at => "/resque"

  resources :repositories, :only => [:new, :show, :create, :update]

  root :to => 'repositories#new'

end

app/models/gemfile.rb
class Gemfile
  include Mongoid::Document

  field :sources, :type => Array, :default => []
  field :body, :type => String

  embedded_in :repository

  def get_used_gems
    if body
      GemfileParser.parse(body).each do |params|
        case params[:type]
        when :source
          sources.push(params[:url])
        when :gem
          params.delete(:type)
          params.delete(:require)
          if params[:group].class == String || params[:group].class == Symbol
            group = params[:group]
            params[:group] = [group]
          end
          repository.used_gems.create(params)
        end
      end
    end
  end
end

app/models/repository.rb
class Repository
  include Mongoid::Document
  include Mongoid::Timestamps

  field :url, :type => String
  field :username, :type => String
  field :name, :type => String

  index :url, :unique => true
  index :username
  index :created_at

  embeds_one :gemfile
  has_many :used_gems, :dependent => :delete

  validates_presence_of :url, :username, :name
  validates_uniqueness_of :url
  validates_format_of :url, with: /https?:\/\/github\.com\/[\w\-]+\/[\w\-]+\/?$/

  before_validation do |record|
    record.url =~ /github\.com\/(.*?)\/(.*)\/?$/
    record.username = $1
    record.name = $2
  end

  after_save do |record|
    record.async_get_gemfile_and_used_gems
  end

  scope :recent, order_by([[:created_at, :desc]])

  def user_url
    "https://github.com/#{self.username}"
  end

  def get_gemfile
    gemfile_body = GithubUtil.get_gemfile_body(self)
    self.create_gemfile({:body => gemfile_body})
  end

  def async_get_gemfile_and_used_gems
    Resque.enqueue(Job::GetUsedGemsJob, self.id)
  end
end

app/models/used_gem.rb
class UsedGem
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, :type => String
  field :url, :type => String
  field :version, :type => String
  field :group, :type => Array
  field :author, :type => String

  referenced_in :repository

  validates_presence_of :name

  before_save do |record|
    record.url = "http://rubygems.org/gems/#{record.name}"
  end

  def self.count_gems
    map = <<-EOS
      function() {
        emit(this.name, 1);
      }
    EOS
    reduce = <<-EOS
      function(name, values) {
        var total = 0;
        values.forEach(function(value) {
          total += value;
        });

        return {gem_count: total};
      }
    EOS

    UsedGem.collection.map_reduce(map, reduce, {out: {replace: "temp_gems"}})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  # GET /repositories
  # GET /repositories.json
  def index
    @repositories = Repository.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @repositories }
    end
  end

  # GET /repositories/1
  # GET /repositories/1.json
  def show
    @repository = Repository.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @repository }
    end
  end

  # GET /repositories/new
  # GET /repositories/new.json
  def new
    @repository = Repository.new
    @repositories = Repository.recent.page(params[:page]).per(20)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @repository }
    end
  end

  # GET /repositories/1/edit
  def edit
    @repository = Repository.find(params[:id])
  end

  # POST /repositories
  # POST /repositories.json
  def create
    @repository = Repository.new(params[:repository])

    respond_to do |format|
      if @repository.save
        format.html { redirect_to root_path, notice: 'Repository was successfully created.' }
        format.json { render json: @repository, status: :created, location: @repository }
      else
        @repositories = Repository.recent.page(params[:page]).per(20)
        format.html { render action: "new" }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /repositories/1
  # PUT /repositories/1.json
  def update
    @repository = Repository.find(params[:id])

    respond_to do |format|
      if @repository.update_attributes(params[:repository])
        format.html { redirect_to root_path, notice: 'Repository was successfully updated.' }
        format.json { head :no_content }
      else
        @repositories = Repository.recent.page(params[:page]).per(20)
        format.html { render action: "edit" }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.json
  def destroy
    @repository = Repository.find(params[:id])
    @repository.destroy

    respond_to do |format|
      format.html { redirect_to repositories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "ja"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : "Gemfile Stats"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    / Le styles
    :css
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    = stylesheet_link_tag "application", :media => "all"
    / Le fav and touch icons
    %link{:href => "images/favicon.ico", :rel => "shortcut icon"}/
    %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/


  %body
    #fb-root
    :javascript
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/ja_JP/all.js#xfbml=1";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => root_path}Gemfilestats

    .container

      .content
        .row
          .span12
            = yield
    
      %footer
        %p &copy; Tomohiro Hashidate 2012

    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = yield(:post_javascript)

app/views/repositories/_form.html.haml
= form_for @repository do |f|
  -if @repository.errors.any?
    #error_explanation
      %h2= "#{pluralize(@repository.errors.count, "error")} prohibited this repository from being saved:"
      %ul
        - @repository.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.text_field :url, :placeholder => "https://github.com/rails/rails"
    = f.submit 'Add', :class => ["btn-primary"]

app/views/repositories/edit.html.haml
%h1 Editing repository

= render 'form'

= link_to 'Show', @repository
\|
= link_to 'Back', repositories_path

app/views/repositories/index.html.haml
%h1 Listing repositories

%table
  %tr
    %th Url
    %th
    %th
    %th

  - @repositories.each do |repository|
    %tr
      %td= repository.url
      %td= link_to 'Show', repository
      %td= link_to 'Edit', edit_repository_path(repository)
      %td= link_to 'Destroy', repository, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Repository', new_repository_path

app/views/repositories/new.html.haml
#add_repository
  %h1 Add Github repository
  %p Repository has Gemfile in Root

  = render 'form'

#recent_repositories
  %h1 Recent 20 Repositories
  %ul#repositories
    - @repositories.each do |repository|
      %li[repository]= link_to repository.username + "/" + repository.name, repository
  = paginate @repositories

app/views/repositories/show.html.haml
- content_for(:title) do
  #{@repository.username}/#{@repository.name} Gemfile
%p#notice= notice

%p
  %span.label
    URL:
  %span.value
    = link_to @repository.url, @repository.url
%p
  %span.label
    USER:
  %span.value
    = link_to @repository.username, @repository.user_url
%p
  %span.label
    NAME:
  %span.value
    = @repository.name

#repository_gemfile
  .fb-like{:data => {:href => request.url, :send => "false", :layout => "box_count", :width => "450"}}
  %h2 Gemfile
  %pre.prettyprint.lang-rb
    = raw @repository.gemfile.body.gsub(/\n/, "<br>")

- content_for(:post_javascript) do
  :javascript
    $(function() {
      prettyPrint();
    });